import { PlayerState } from '../interfaces/interfaces/player-state.interface';

export const bots: PlayerState[] = [
  {
    playerId: 'bot1',
    username: 'Bot Alpha',
    hp: 100,
    attack: 15,
    defense: 5,
    speed: 10,
    specialAbility: 'Fireball',
    isBot: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    playerId: 'bot2',
    username: 'Bot Bravo',
    hp: 90,
    attack: 18,
    defense: 4,
    speed: 12,
    specialAbility: 'Ice Blast',
    isBot: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    playerId: 'bot3',
    username: 'Bot Charlie',
    hp: 110,
    attack: 12,
    defense: 6,
    speed: 8,
    specialAbility: 'Thunder Strike',
    isBot: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    playerId: 'bot4',
    username: 'Bot Delta',
    hp: 95,
    attack: 14,
    defense: 7,
    speed: 9,
    specialAbility: 'Poison Dart',
    isBot: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    playerId: 'bot5',
    username: 'Bot Echo',
    hp: 105,
    attack: 13,
    defense: 5,
    speed: 11,
    specialAbility: 'Wind Slash',
    isBot: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    playerId: 'bot6',
    username: 'Bot Foxtrot',
    hp: 100,
    attack: 16,
    defense: 6,
    speed: 10,
    specialAbility: 'Earthquake',
    isBot: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
